env:
- GH_USER=gheeci GH_REPO=ghee_test GH_ORG=ghee-org
language: ruby
notifications:
  slack:
    secure: WSsWVhP3oeWyUHtpia+qKJ3GEd3jOO7I9TLEMbB8mSy2EDy137wXi6YvhOKOmThO7Fr9LrlPi2C8pjtD5fg7bfR+JmRrUGGYTLpFJGUartums3ThpR2i6KCT+l3+009FpCKODZHt2jnSCCcHy9+6FYwfnjTPxqxK4rMtGf5QV9g=
script: bundle exec rake spec
before_install:
- gem install bundler -v 1.12
